services:
  dockerlistener:
    build: .
    container_name: dockerlistener
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=ton_token
      - TELEGRAM_CHAT_ID=ton_chat_id
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data